"""Initial migration.

Revision ID: 4bd4ec556815
Revises: 
Create Date: 2024-08-26 21:26:49.188004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd4ec556815'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('nota_primeiro_semestre', sa.Float(), nullable=False),
    sa.Column('nota_segundo_semestre', sa.Float(), nullable=False),
    sa.Column('nome_professor', sa.String(length=100), nullable=False),
    sa.Column('numero_sala', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    # ### end Alembic commands ###
